//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticsShop.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Owner()
        {
            this.CityObject = new HashSet<CityObject>();
        }
    
        public int Id { get; set; }
        public string Supervisor_First_Name { get; set; }
        public string Supervisor_Second_Name { get; set; }
        public string Supervisor_Patronymic { get; set; }
        public string Phone { get; set; }
        public string TypeLegal { get; set; }
        public string NameOwner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CityObject> CityObject { get; set; }
    }
}
